package craft

import (
	"errors"
	"strings"
	"testing"

	dhntskills "github.com/dhnt/dhnt/skills"
)

// stubCompleter replies with a fixed string, recording whether it was called.
func stubCompleter(reply string, called *bool) dhntskills.Completer {
	return func(prompt string) (string, error) {
		if called != nil {
			*called = true
		}
		return reply, nil
	}
}

// THE GATE. An under-banded decomposition is worse than none: a
// plausible-but-wrong contract is a promise nobody verified, and every later
// reader inherits it. So the constructor refuses rather than degrading.
func TestNewNormaliser_RefusesUnderBanded(t *testing.T) {
	for _, band := range []int{0, 1, 2} {
		t.Run("band", func(t *testing.T) {
			got, err := NewNormaliser(stubCompleter("", nil), NormaliserOptions{Band: band})
			if !errors.Is(err, ErrUnderBanded) {
				t.Errorf("band %d: err = %v, want ErrUnderBanded", band, err)
			}
			if got != nil {
				t.Errorf("band %d returned a usable normaliser", band)
			}
		})
	}
}

// An UNDECLARED band is not a passing band. Defaulting to permissive here would
// make the gate decorative, since the common case is an operator who simply did
// not pass the flag.
func TestNewNormaliser_UndeclaredBandIsRefused(t *testing.T) {
	if _, err := NewNormaliser(stubCompleter("", nil), NormaliserOptions{}); !errors.Is(err, ErrUnderBanded) {
		t.Errorf("an undeclared band was accepted: %v", err)
	}
}

func TestNewNormaliser_AcceptsBand3AndAbove(t *testing.T) {
	for _, band := range []int{3, 4} {
		got, err := NewNormaliser(stubCompleter("", nil), NormaliserOptions{Band: band})
		if err != nil {
			t.Errorf("band %d: %v", band, err)
		}
		if got == nil {
			t.Errorf("band %d returned no normaliser", band)
		}
	}
}

func TestNewNormaliser_RequiresACompleter(t *testing.T) {
	if _, err := NewNormaliser(nil, NormaliserOptions{Band: 4}); err == nil {
		t.Error("a nil completer was accepted")
	}
}

// A reply that parses but states no postcondition has not answered the only
// question worth asking. It must quarantine, not admit a skill that guarantees
// nothing under a name implying it does.
func TestNormaliser_RejectsContractlessResult(t *testing.T) {
	// dhnt's Normalise parses the model's reply as LAYER-1 CNL in the source
	// language, not as canonical dhnt — so the stub reply is generated by
	// linearising a real skill into English rather than hand-written. That also
	// keeps the fixture honest: if the CNL surface changes, this regenerates
	// with it instead of silently testing a format nobody emits any more.
	g, err := dhntskills.SeedGlossary()
	if err != nil {
		t.Fatal(err)
	}
	contractless := dhntskills.Skill{
		Name:      "sinakota",
		EffectCap: []dhntskills.Effect{dhntskills.EffRead},
	}
	cnl, err := dhntskills.LineariseLang(contractless, g, "en")
	if err != nil {
		t.Fatal(err)
	}
	reply := "<dhnt>" + cnl + "</dhnt>"
	norm, err := NewNormaliser(stubCompleter(reply, nil), NormaliserOptions{Band: 4, Retries: 1})
	if err != nil {
		t.Fatal(err)
	}

	_, err = norm(Candidate{Name: "prose", Body: "do a thing"})
	if err == nil {
		t.Fatal("a contract-less normalisation was accepted")
	}
	if !strings.Contains(err.Error(), "contract") {
		t.Errorf("error should name the missing contract, got: %v", err)
	}
}

// Nothing to normalise is an error, not an empty skill.
func TestNormaliser_RequiresProse(t *testing.T) {
	called := false
	norm, err := NewNormaliser(stubCompleter("", &called), NormaliserOptions{Band: 4})
	if err != nil {
		t.Fatal(err)
	}
	if _, err := norm(Candidate{Name: "empty"}); err == nil {
		t.Error("a candidate with no prose was accepted")
	}
	if called {
		t.Error("the model was called for a candidate with nothing to read")
	}
}

// Description stands in when there is no body — a one-line skill is still a
// skill, and refusing it would drop real content on a technicality.
func TestNormaliser_FallsBackToDescription(t *testing.T) {
	called := false
	norm, err := NewNormaliser(stubCompleter("not parsable", &called), NormaliserOptions{Band: 4, Retries: 1})
	if err != nil {
		t.Fatal(err)
	}
	_, _ = norm(Candidate{Name: "d", Description: "verify the build and tests pass"})
	if !called {
		t.Error("the model was not called even though a description was present")
	}
}

// The band gate must hold end-to-end through Study, not only at construction.
func TestStudy_UnderBandedNormaliserNeverRuns(t *testing.T) {
	if _, err := NewNormaliser(stubCompleter("anything", nil), NormaliserOptions{Band: 2}); err == nil {
		t.Fatal("construction should have failed")
	}
	// With no normaliser available, prose quarantines rather than being guessed.
	rep := Study([]Candidate{{
		Name:   "prose",
		Body:   "some instructions",
		Source: Source{License: "MIT"},
	}}, nil, nil)

	if got := rep.Outcomes[0].Disposition; got != DispQuarantined {
		t.Errorf("disposition = %s, want quarantined", got)
	}
}

func TestExecCompleter_RejectsEmptyCommand(t *testing.T) {
	if _, err := ExecCompleter("")("prompt"); err == nil {
		t.Error("an empty command was accepted")
	}
	if _, err := ExecCompleter("   ")("prompt"); err == nil {
		t.Error("a whitespace-only command was accepted")
	}
}
