// Copyright (c) 2025 qiangli
// See LICENSE for licensing information

package dag

import (
	"bytes"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"

	"gopkg.in/yaml.v3"

	"github.com/qiangli/coreutils/pkg/weavecli"
)

// A dag file stays a dag file — it is bashy's own format. What other agentic
// tools discover is an Agent Skill: a directory holding SKILL.md whose
// frontmatter `name`/`description` is the routing surface. `--skill DIR`
// projects the dag into that shape: a thin skill that routes the agent to the
// targets and says how to run them through bashy, never a copy of the bodies
// (dependency order, up-to-date skipping and effect caps live in `bashy dag`).

// skillMarker is written into every generated SKILL.md; a re-run overwrites a
// file that carries it and refuses to clobber one that does not.
const skillMarker = "bashy dag --skill"

type skillResult struct {
	File  string `json:"file"`
	Skill string `json:"skill"`
	Name  string `json:"name"`
}

func runSkill(out, errOut io.Writer, mode weavecli.OutputMode, doc *Document, outDir string) error {
	name := skillName(doc)
	if name == "" {
		return emitErr(errOut, mode, errf(weavecli.ExitInvalidArg,
			"--skill: cannot derive a skill name; add `name:` to the frontmatter of %s", doc.Path))
	}
	dest := filepath.Join(outDir, name, "SKILL.md")
	if old, err := os.ReadFile(dest); err == nil && !bytes.Contains(old, []byte(skillMarker)) {
		return emitErr(errOut, mode, errf(weavecli.ExitInvalidArg,
			"--skill: %s exists and was not generated by %s; refusing to overwrite", dest, skillMarker))
	}
	body, err := renderSkill(doc, name, skillDagRef(doc.Path))
	if err != nil {
		return emitErr(errOut, mode, errf(weavecli.ExitGenericFail, "--skill: %v", err))
	}
	if err := os.MkdirAll(filepath.Dir(dest), 0o755); err != nil {
		return emitErr(errOut, mode, errf(weavecli.ExitGenericFail, "--skill: %v", err))
	}
	tmp := dest + ".tmp"
	if err := os.WriteFile(tmp, body, 0o644); err != nil {
		return emitErr(errOut, mode, errf(weavecli.ExitGenericFail, "--skill: %v", err))
	}
	if err := os.Rename(tmp, dest); err != nil {
		os.Remove(tmp)
		return emitErr(errOut, mode, errf(weavecli.ExitGenericFail, "--skill: %v", err))
	}
	if mode == weavecli.OutputJSON {
		emitOK(out, skillResult{File: doc.Path, Skill: dest, Name: name})
		return nil
	}
	fmt.Fprintf(out, "skill: %s\n", dest)
	return nil
}

// skillName is the frontmatter name, or the dag file's directory name,
// folded to the Agent Skills shape (lowercase, digits, single hyphens, ≤64).
func skillName(doc *Document) string {
	src := doc.Name
	if src == "" {
		abs, _ := filepath.Abs(doc.Path)
		src = filepath.Base(filepath.Dir(abs))
	}
	var b strings.Builder
	dash := false
	for _, r := range strings.ToLower(src) {
		if (r >= 'a' && r <= 'z') || (r >= '0' && r <= '9') {
			b.WriteRune(r)
			dash = false
		} else if !dash && b.Len() > 0 {
			b.WriteByte('-')
			dash = true
		}
	}
	s := strings.TrimRight(b.String(), "-")
	if len(s) > 64 {
		s = strings.TrimRight(s[:64], "-")
	}
	return s
}

// skillDagRef is how the skill names the dag file: relative to the working
// directory (the repo root an agent runs from) when it lies beneath it, so a
// generated skill never carries a host path.
func skillDagRef(path string) string {
	abs, err := filepath.Abs(path)
	if err != nil {
		return filepath.ToSlash(path)
	}
	if wd, err := os.Getwd(); err == nil {
		if rel, err := filepath.Rel(wd, abs); err == nil && !strings.HasPrefix(rel, "..") {
			return filepath.ToSlash(rel)
		}
	}
	return filepath.Base(abs)
}

// skillDescription is the routing sentence: what the file does, then WHEN to
// use it with the target names as trigger words. One line, no angle brackets,
// at most 1024 characters (the Agent Skills limits).
func skillDescription(doc *Document, name string) string {
	what := strings.Join(strings.Fields(doc.Desc), " ")
	if what == "" {
		what = "Task graph for " + name
	}
	what = strings.TrimRight(what, ".") + "."
	targets := doc.Order
	if len(targets) > 12 {
		targets = targets[:12]
	}
	when := " Use when asked to run, build or test " + name
	if len(targets) > 0 {
		when += " (targets: " + strings.Join(targets, ", ") + ")"
	}
	when += "; run the targets through bashy dag, not by hand."
	s := strings.NewReplacer("<", "", ">", "").Replace(what + when)
	if len(s) > 1024 {
		s = s[:1021] + "..."
	}
	return s
}

func renderSkill(doc *Document, name, ref string) ([]byte, error) {
	var fm bytes.Buffer
	enc := yaml.NewEncoder(&fm)
	enc.SetIndent(2)
	type skillMeta struct {
		DagFile     string `yaml:"dag-file"`
		GeneratedBy string `yaml:"generated-by"`
	}
	if err := enc.Encode(struct {
		Name        string    `yaml:"name"`
		Description string    `yaml:"description"`
		Metadata    skillMeta `yaml:"metadata"`
	}{name, skillDescription(doc, name), skillMeta{ref, skillMarker}}); err != nil {
		return nil, err
	}
	enc.Close()

	cmd := "bashy dag -f " + ref
	var b bytes.Buffer
	fmt.Fprintf(&b, "---\n%s---\n\n# %s\n\n", fm.String(), name)
	if d := strings.TrimSpace(doc.Desc); d != "" {
		fmt.Fprintf(&b, "%s\n\n", d)
	}
	fmt.Fprintf(&b, "This repo's tasks live in `%s`, a bashy dag file: markdown targets with\n"+
		"`Requires:` edges, `Sources:`/`Generates:` up-to-date checks and `Effects:` caps.\n"+
		"Run targets through `bashy dag` — it orders dependencies, skips up-to-date\n"+
		"work and enforces the caps. Do not copy the fenced bodies into a shell.\n"+
		"Read `%s` itself for a target's full recipe.\n\n", ref, ref)
	b.WriteString("## Commands\n\n```bash\n")
	fmt.Fprintf(&b, "%s --list              # targets and what they do\n", cmd)
	fmt.Fprintf(&b, "%s TARGET              # run TARGET (its requirements first)\n", cmd)
	fmt.Fprintf(&b, "%s --dryrun TARGET     # the plan, running nothing\n", cmd)
	fmt.Fprintf(&b, "%s --json TARGET       # machine-readable result envelope\n", cmd)
	b.WriteString("```\n\n")
	if d := defaultTarget(doc); d != "" {
		fmt.Fprintf(&b, "With no target, `%s` runs `%s`.\n\n", cmd, d)
	}
	if len(doc.Order) > 0 {
		b.WriteString("## Targets\n\n| target | requires | what |\n|---|---|---|\n")
		cell := strings.NewReplacer("|", `\|`, "\n", " ")
		for _, n := range doc.Order {
			t, _ := doc.Lookup(n)
			fmt.Fprintf(&b, "| `%s` | %s | %s |\n", n,
				cell.Replace(strings.Join(t.Requires, ", ")), cell.Replace(firstSentence(t.Desc)))
		}
		b.WriteString("\n")
	}
	b.WriteString("## Getting bashy\n\n" +
		"`bashy` is a single binary (https://github.com/qiangli/bashy, releases page).\n" +
		"If it is not on PATH, ask the user to install it rather than emulating a target.\n\n" +
		"<!-- generated by " + skillMarker + "; regenerate instead of editing -->\n")
	return b.Bytes(), nil
}

// firstSentence is a target's summary for the table: its first paragraph
// unwrapped (dag prose is hard-wrapped), cut after the first sentence and
// capped, so a row never ends mid-clause the way the first line does.
func firstSentence(desc string) string {
	para, _, _ := strings.Cut(strings.TrimSpace(desc), "\n\n")
	s := strings.Join(strings.Fields(para), " ")
	if i := strings.Index(s, ". "); i >= 0 {
		s = s[:i+1]
	}
	if r := []rune(s); len(r) > 160 {
		s = strings.TrimSpace(string(r[:159])) + "…"
	}
	return s
}
