// Copyright (c) 2025 qiangli
// See LICENSE for licensing information

// Package webterm serves a real terminal to a browser: one PTY per WebSocket,
// running bashy itself.
//
// It runs the SHELL BINARY rather than embedding an interpreter. Outpost's
// /shell endpoint (internal/agent/shell) takes the other route — it builds an
// mvdan.cc/sh interp.Runner in-process — and that route is not available here
// for a reason worth stating: bashy's bare-name verb shims are generated by
// agentos.Preamble() inside bashy's own internal package, so an embedded runner
// would serve a terminal where `meet --help` says "command not found", and
// would separately re-derive rc files, history, exec history, presence, and
// --posix handling. Spawning the binary makes the terminal bashy BY
// CONSTRUCTION; there is nothing to keep in sync. The cost is one child process
// per browser tab, which is what every web terminal pays.
//
// The wire protocol is the one outpost's /shell already speaks, so an existing
// xterm.js client works unchanged:
//
//	server -> client   binary   raw PTY bytes
//	client -> server   binary   raw stdin bytes
//	client -> server   text     {"type":"size","cols":N,"rows":N}
//	client -> server   text     anything else -> forwarded as stdin
package webterm

import (
	"context"
	"encoding/json"
	"errors"
	"log/slog"
	"net/http"
	"os"
	"os/exec"
	"path"
	"strconv"
	"time"

	"github.com/gorilla/websocket"

	"github.com/qiangli/yoke/pkg/coopauth"
)

// sizeMsg is the JSON text-frame schema the browser sends on resize. Same shape
// outpost's /shell uses — do not diverge, clients are shared.
type sizeMsg struct {
	Type string `json:"type"`
	Cols uint16 `json:"cols"`
	Rows uint16 `json:"rows"`
}

// Options configures the terminal endpoint.
type Options struct {
	// Shell is the argv to run. Empty means this binary with -i, resolved via
	// os.Executable() — the terminal is the same bashy that is serving it.
	Shell []string
	// Dir is the working directory; empty means the server's own.
	Dir string
	// Env is appended to the server's environment.
	Env []string
}

func (o Options) argv() []string {
	if len(o.Shell) > 0 {
		return o.Shell
	}
	if exe, err := os.Executable(); err == nil && exe != "" {
		return []string{exe, "-i"}
	}
	if p, err := exec.LookPath("bashy"); err == nil {
		return []string{p, "-i"}
	}
	if sh := os.Getenv("SHELL"); sh != "" {
		return []string{sh, "-i"}
	}
	return []string{"/bin/sh", "-i"}
}

// upgrader rejects cross-origin upgrades.
//
// Outpost's equivalent sets InsecureSkipVerify because its listener is
// loopback-only behind a tunnel that has already enforced same-origin. The
// console can be bound to a LAN address, so it cannot inherit that assumption:
// an attacker's page must not be able to open a shell on the viewer's machine.
// An absent Origin (a non-browser client) is allowed; a present one must match
// the address the browser thinks it is talking to.
var upgrader = websocket.Upgrader{
	ReadBufferSize:  4096,
	WriteBufferSize: 4096,
	CheckOrigin: func(r *http.Request) bool {
		o := r.Header.Get("Origin")
		return o == "" || o == coopauth.ExternalBase(r)
	},
}

// Handler returns the terminal panel: the socket at ./ws, and a page at
// everything else. Callers gate it themselves — this hands out a shell running
// as the server's user and is exactly as privileged as that user.
//
// The split matters. An earlier version upgraded on ANY path, so a browser
// following the tile's own link got gorilla's raw 400 ("not using the websocket
// protocol") instead of a terminal — a broken door at the exact URL the start
// page advertises.
func Handler(opts Options) http.Handler {
	socket := SocketHandler(opts)
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if path.Base(r.URL.Path) == "ws" {
			socket.ServeHTTP(w, r)
			return
		}
		servePage(w, r)
	})
}

// SocketHandler is the WebSocket half on its own, for a host that serves the
// terminal's PAGE itself — which the launcher does, so the terminal is a real
// full-browser page rather than something framed inside another app.
func SocketHandler(opts Options) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if !Supported() {
			http.Error(w, "terminal: no pseudo-console on this platform", http.StatusNotImplemented)
			return
		}

		cols, rows := uint16(80), uint16(24)
		if v, err := strconv.Atoi(r.URL.Query().Get("cols")); err == nil && v > 0 && v < 1<<16 {
			cols = uint16(v)
		}
		if v, err := strconv.Atoi(r.URL.Query().Get("rows")); err == nil && v > 0 && v < 1<<16 {
			rows = uint16(v)
		}

		ws, err := upgrader.Upgrade(w, r, nil)
		if err != nil {
			// Upgrade already wrote the error response.
			slog.Debug("webterm upgrade", "err", err)
			return
		}
		// A normal end (the shell exited) must arrive as a close FRAME, not as a
		// dropped TCP connection: the browser reports the latter as code 1006,
		// which is indistinguishable from a network failure, so a shell that
		// quits during startup looks like a broken console instead of a shell
		// that quit.
		closeReason := "session ended"
		defer func() {
			_ = ws.WriteControl(websocket.CloseMessage,
				websocket.FormatCloseMessage(websocket.CloseNormalClosure, closeReason),
				time.Now().Add(time.Second))
			ws.Close()
		}()

		sess, err := start(opts, cols, rows)
		if err != nil {
			slog.Error("webterm start", "err", err)
			_ = ws.WriteMessage(websocket.TextMessage, []byte("terminal: "+err.Error()+"\r\n"))
			return
		}
		defer sess.Close()

		started := time.Now()
		ctx, cancel := context.WithCancel(r.Context())
		defer cancel()

		// PTY -> client.
		go func() {
			defer cancel()
			buf := make([]byte, 4096)
			for {
				n, err := sess.Read(buf)
				if n > 0 {
					if werr := ws.WriteMessage(websocket.BinaryMessage, buf[:n]); werr != nil {
						slog.Warn("webterm write", "err", werr)
						return
					}
				}
				if err != nil {
					slog.Debug("webterm pty read", "err", err)
					return
				}
			}
		}()

		// The child exiting is what ends the session.
		go func() {
			defer cancel()
			werr := sess.wait()
			if werr != nil {
				closeReason = "shell exited: " + werr.Error()
				slog.Warn("webterm child exit", "err", werr)
				return
			}
			// Exiting cleanly within a moment of starting is almost never what
			// the operator wanted: it means the login shell's own startup files
			// ended the session. Say so, because the alternative is a blank pane
			// and no way to tell it from a bug in the console.
			if time.Since(started) < 2*time.Second {
				closeReason = "the shell exited immediately — check its startup files (~/.bashrc, ~/.bash_profile)"
				slog.Warn("webterm shell exited during startup",
					"shell", opts.argv()[0], "note", "runs the same under a plain `bash -i`")
			}
		}()

		// Closing the socket must unblock the foreground read.
		go func() {
			<-ctx.Done()
			_ = ws.SetReadDeadline(time.Now())
		}()

		// client -> PTY.
		for {
			typ, data, err := ws.ReadMessage()
			if err != nil {
				return
			}
			switch typ {
			case websocket.TextMessage:
				var m sizeMsg
				if err := json.Unmarshal(data, &m); err == nil && m.Type == "size" {
					_ = sess.resize(m.Cols, m.Rows)
					continue
				}
				if _, err := sess.Write(data); err != nil {
					return
				}
			case websocket.BinaryMessage:
				if _, err := sess.Write(data); err != nil {
					return
				}
			}
		}
	})
}

// errUnsupported is returned by start on a platform with no pseudo-console.
var errUnsupported = errors.New("webterm: no pseudo-console on this platform")
