package sota

import (
	"regexp"
	"strings"
	"time"

	"github.com/qiangli/yoke/pkg/kb"
)

// kbStore resolves the HOST kb store (never the committed repo docs/kb/). A sota
// report is GENERAL knowledge — "the SOTA on X" is the same in every repo and is
// not "true of THIS repo" — so it caches host-wide (reused across repos) and must
// NOT pollute a repo's committed kb. Cached as a kb page so it stays discoverable
// and the same durable memory the fleet shares.
func kbStore() *kb.Store {
	dir := strings.TrimSpace(kb.DefaultDir())
	if dir == "" {
		return nil
	}
	return kb.Open(dir)
}

var slugRe = regexp.MustCompile(`[^a-z0-9]+`)

func slugify(q string) string {
	s := slugRe.ReplaceAllString(strings.ToLower(q), "-")
	s = strings.Trim(s, "-")
	if len(s) > 60 {
		s = s[:60]
	}
	return "sota-" + s
}

// cachedFresh returns the cached page if it exists AND is within maxAge — the
// reuse gate (research once, many read; do not re-spend on a fresh question).
func cachedFresh(store *kb.Store, slug string, maxAge time.Duration) (*kb.Page, bool) {
	if store == nil {
		return nil, false
	}
	p, err := store.Load(slug)
	if err != nil || p == nil {
		return nil, false
	}
	ts := p.Updated
	if ts == "" {
		ts = p.Created
	}
	t, perr := time.Parse(time.RFC3339, ts)
	if perr != nil {
		return p, false
	}
	if maxAge > 0 && time.Since(t) > maxAge {
		return p, false // exists but stale
	}
	return p, true
}

// cacheReport writes (or updates) the sota page in kb.
func cacheReport(store *kb.Store, slug, question, report string) error {
	if store == nil {
		return nil
	}
	op, created := "add", ""
	if old, err := store.Load(slug); err == nil && old != nil {
		op, created = "update", old.Created
	}
	return store.Write(&kb.Page{
		Slug:        slug,
		Type:        "fact",
		Title:       "SOTA — " + question,
		Description: "Current state-of-the-art on " + question + " (auto-generated by bashy sota; cited + dated)",
		Tags:        []string{"sota", "research"},
		Created:     created,
		Body:        report,
	}, op)
}
