#!/usr/bin/env bash
# Regenerate THIRD_PARTY_GRAMMARS.md: the license of every tree-sitter grammar
# whose parse tables gotreesitter embeds into the binary. Reads the pinned
# module's grammars/languages.lock, asks the GitHub license API per repository
# (authenticated gh), applies the hand-verified overrides below for repos whose
# license lives only in package.json/Cargo.toml, and refuses to finish if any
# grammar resolves to a non-permissive or unknown license. Run on every
# gotreesitter bump; commit the output.
set -euo pipefail
cd "$(dirname "$0")/.."
ver=$(go list -m -f '{{.Version}}' github.com/odvcencio/gotreesitter)
dir=$(go list -m -f '{{.Dir}}' github.com/odvcencio/gotreesitter)
lock="$dir/grammars/languages.lock"
out=THIRD_PARTY_GRAMMARS.md
tmp=$(mktemp)
prior=$(mktemp)
cp "$out" "$prior"
trap 'rm -f "$tmp" "$prior"' EXIT
# name<TAB>license<TAB>evidence — repos whose license file the API cannot see.
overrides='
authzed	MIT	package.json
brightscript	ISC	package.json
cooklang	ISC	package.json
corn	MIT	package.json
eds	MIT	Cargo.toml/tree-sitter.json
eex	MIT	package.json
elsa	MIT	package.json
facility	MIT	package.json
move	MIT	package.json
wat	Apache-2.0 WITH LLVM-exception	LICENSE
'
grep -v '^#' "$lock" | while read -r name url commit _; do
  repo=${url#https://github.com/}; repo=${repo%/}
  ov=$(printf '%s\n' "$overrides" | awk -F'\t' -v n="$name" '$1==n{print $2"\t"$3}')
  if [ -n "$ov" ]; then lic=${ov%%$'\t'*}; how=${ov#*$'\t'}
  else
    lic=$(gh api "repos/$repo/license" --jq '.license.spdx_id' 2>/dev/null || true)
    if [ -z "$lic" ]; then
      lic=$(curl -fsSL -H 'Accept: application/vnd.github+json' "https://api.github.com/repos/$repo/license" 2>/dev/null | python3 -c 'import json,sys; print((json.load(sys.stdin).get("license") or {}).get("spdx_id") or "")' 2>/dev/null || true)
    fi
    how="GitHub license API"
    if [ -z "$lic" ]; then
      cached=$(awk -F'|' -v repo="https://github.com/$repo" -v commit="${commit:0:12}" '$3 ~ repo && $4 ~ commit {gsub(/^[[:space:]]+|[[:space:]]+$/, "", $5); gsub(/\\*/, "", $5); gsub(/^[[:space:]]+|[[:space:]]+$/, "", $6); sub(/ \(cached for unchanged grammar commit\).*/, "", $6); print $5 "\t" $6; exit}' "$prior")
      if [ -n "$cached" ]; then lic=${cached%%$'\t'*}; how="${cached#*$'\t'} (cached for unchanged grammar commit)"; fi
    fi
    [ -z "$lic" ] && lic=UNKNOWN
  fi
  printf '%s\t%s\t%s\t%s\t%s\n' "$name" "$repo" "$commit" "$lic" "$how"
done | sort > "$tmp"
python3 - "$tmp" "$out" "$ver" <<'PY'
import sys
rows=[l.rstrip("\n").split("\t") for l in open(sys.argv[1]) if l.strip()]
perm={"MIT","Apache-2.0","ISC","Unlicense","CC0-1.0","Apache-2.0 WITH LLVM-exception","BSD-2-Clause","BSD-3-Clause"}
bad=[r for r in rows if r[3] not in perm]
with open(sys.argv[2],"w") as f:
    f.write("# Tree-sitter grammar attributions\n\n")
    f.write("The `ast` code-intelligence verbs (`pkg/treesitter`, `cmds/ast`) link\n`github.com/odvcencio/gotreesitter` (MIT), which embeds parse tables compiled\nfrom the upstream tree-sitter grammar repositories below. A grammar table is\ndata derived from that grammar's `parser.c`, so each grammar's own license\napplies to the bytes in the binary. Generated by `scripts/grammar-licenses.sh`\nfrom the pinned module's `grammars/languages.lock`; regenerate on every\ngotreesitter bump and read the result before pinning.\n\n")
    f.write("Policy: compiled-in means permissive only (bashy\n`docs/licensing-supply-chain-policy.md` §1). Any grammar under EXCLUDED\nis non-permissive and must not be linked into any shipped binary.\n\n")
    f.write(f"Generated against gotreesitter {sys.argv[3]}: {len(rows)} grammars, {len(rows)-len(bad)} permissive, {len(bad)} excluded.\n\n")
    f.write("## EXCLUDED (non-permissive)\n\n| grammar | repository | commit | license |\n|---|---|---|---|\n")
    for n,r,c,l,h in bad: f.write(f"| `{n}` | https://github.com/{r} | `{c[:12]}` | **{l}** |\n")
    f.write("\n## Included\n\n| grammar | repository | commit | license | evidence |\n|---|---|---|---|---|\n")
    for n,r,c,l,h in rows:
        if [n,r,c,l,h] not in bad: f.write(f"| `{n}` | https://github.com/{r} | `{c[:12]}` | {l} | {h} |\n")
print(f"{len(rows)} grammars, {len(bad)} non-permissive or unknown: {[b[0] for b in bad]}")
if bad: sys.exit("non-permissive or UNKNOWN license present — remove the grammar or add a verified permissive override")
PY
